server:
  port: 8080

spring:
  application:
    name: fixit-ops-management
  main:
    banner-mode: console
  datasource:
    url: jdbc:postgresql://localhost:5432/fixit_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: users
        jdbc:
          time_zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs

